name: 同步远程仓库

on:
  schedule:
    - cron: '0 */24 * * *'  # 每8小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 配置Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: 同步远程仓库
        run: |
          git remote add upstream https://github.com/cmliu/CF-Workers-docker.io.git
          git fetch upstream
          git checkout main
          git merge upstream/main -X ours || true
          git status | grep "both modified:" | awk '{print $3}' | xargs -I {} git checkout --ours {}
          git add .
          git commit -m "自动同步并解决冲突,保留本地更改" || true
          git push origin main

      - name: 检查同步状态
        run: |
          if git status | grep -q "nothing to commit"; then
            echo "同步成功,没有冲突"
          else
            echo "同步完成,但可能存在未解决的问题,请检查"
          fi
